### ISSUE TITLE
Incorrect Target Triple on macOS and 32-bit Linux

### ISSUE THREAD

**Issue by wagenet** [sagiegurari/rust_info#3]
**Describe the bug**

On macOS, `target_triple` returns `x86_64-apple-macos-`. It should be `x86_64-apple-darwin`.

**To Reproduce**
I discovered this using `CARGO_MAKE_RUST_TARGET_TRIPLE` in cargo make.

**Comment by sagiegurari** [comment]
thanks a lot for opening the issue. I'll take a look at it.

**Comment by wagenet** [comment]
I'm also seeing `x86-unknown-linux-gnu` when it seems it should be `i686-unknown-linux-gnu`.

**Comment by sagiegurari** [comment]
I'm pretty sure its based on your rust installation, not on your machine.

**Comment by sagiegurari** [comment]
@wagenet  can you run ```rustc --print cfg``` on your linux and tell me what you have in target_arch? my guess its x86 and not i686 which is what you installed.

**Comment by sagiegurari** [comment]
deleted the nonsense i wrote before.
anyway, it does seem like an issue. i'm trying to see how to mitigate it now in a normal way :)

**Comment by sagiegurari** [comment]
A fix has been released in the new 0.3.1 version.
I hope its solved correctly as i did verify with rustc values and compared with rustup triple values and built a whole set of tests with specific values.

**Comment by wagenet** [comment]
Thanks!
